version: '3.8'

services:
  valkey:
    image: valkey/valkey:latest
    container_name: valkey_container
    restart: always
    ports:
      - "${VALKEY_PORT}:6379"
    volumes:
      - valkey_data:/data

  app:
    build: .
    container_name: node_app
    restart: always
    depends_on:
      - valkey
    environment:
      - DB_HOST=oly1t.h.filess.io
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=3305
      - VALKEY_HOST=valkey
      - VALKEY_PORT=6379
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
    command: ["node", "index.js"]

volumes:
  valkey_data:
